import { describe, it, expect, beforeAll, beforeEach, afterEach, vi } from "vitest";
import { join } from "node:path";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { createLogger } from "../../utils/logger.js";
import { AgentDBMemory } from "./agentdb-memory.js";
import { MemoryTier } from "./unified-memory.interface.js";

// Initialize logger for tests
beforeAll(() => {
  createLogger("error", "test.log");
});

describe("AgentDBMemory", () => {
  let tempDir: string;
  let memory: AgentDBMemory;

  beforeEach(async () => {
    tempDir = mkdtempSync(join(tmpdir(), "agentdb-test-"));
    memory = new AgentDBMemory({
      dbPath: tempDir,
      dimensions: 128, // Smaller for testing
      maxEntriesPerTier: {
        [MemoryTier.Working]: 10,
        [MemoryTier.Ephemeral]: 50,
        [MemoryTier.Persistent]: 100,
      },
      hnswParams: {
        efConstruction: 50,
        M: 8,
        efSearch: 32,
      },
      quantizationType: "none",
      cacheSize: 100,
      enableAutoTiering: true,
      ephemeralTtlMs: 1000, // 1 second for testing
    });
    await memory.initialize();
  });

  afterEach(async () => {
    await memory.shutdown();
    rmSync(tempDir, { recursive: true, force: true });
  });

  // ---------------------------------------------------------------------------
  // isHashBasedEmbedding (private — tested via cast)
  // ---------------------------------------------------------------------------

  describe("isHashBasedEmbedding", () => {
    it("should detect hash-based embeddings (all non-negative values)", () => {
      // Hash fallback produces all-positive normalized vectors
      const hashEmbedding = new Array(128).fill(0).map((_, i) => (i + 1) / 128);
      // Normalize
      const mag = Math.sqrt(hashEmbedding.reduce((a: number, b: number) => a + b * b, 0));
      const normalized = hashEmbedding.map((v: number) => v / mag);

      const result = (memory as any).isHashBasedEmbedding("some text content", normalized);
      expect(result).toBe(true);
    });

    it("should not flag real embeddings (has negative values)", () => {
      // Real neural embeddings contain negative components
      const realEmbedding = new Array(128).fill(0).map((_, i) =>
        i % 2 === 0 ? 0.1 * (i + 1) : -0.05 * (i + 1),
      );

      const result = (memory as any).isHashBasedEmbedding("some text content", realEmbedding);
      expect(result).toBe(false);
    });

    it("should handle empty array", () => {
      const result = (memory as any).isHashBasedEmbedding("some text", []);
      expect(result).toBe(false);
    });

    it("should handle single element array", () => {
      // Single positive element — all non-negative, treated as hash-based
      const result = (memory as any).isHashBasedEmbedding("some text", [0.5]);
      expect(result).toBe(true);
    });

    it("should handle null/undefined embedding", () => {
      expect((memory as any).isHashBasedEmbedding("text", null)).toBe(false);
      expect((memory as any).isHashBasedEmbedding("text", undefined)).toBe(false);
    });

    it("should detect zero vector from empty content as hash-based", () => {
      const zeroVector = new Array(128).fill(0);
      // Empty content with all-zero embedding (hash fallback of empty string)
      const result = (memory as any).isHashBasedEmbedding("", zeroVector);
      // Empty array check passes first, but content.length === 0 returns true
      expect(result).toBe(true);
    });

    it("should detect hash embedding generated by the actual hash fallback", async () => {
      // Store a note without an embedding provider — uses hash fallback internally
      const entry = await memory.storeNote("Test content for hash detection", ["test"]);
      const storedEntry = (memory as any).entries.get(entry.id);
      const embedding = storedEntry?.embedding as number[];

      if (embedding && embedding.length > 0) {
        const result = (memory as any).isHashBasedEmbedding("Test content for hash detection", embedding);
        expect(result).toBe(true);
      }
    });

    it("should not flag embedding with even a single negative value", () => {
      const almostAllPositive = new Array(128).fill(0.1);
      almostAllPositive[64] = -0.001; // One negative value

      const result = (memory as any).isHashBasedEmbedding("text", almostAllPositive);
      expect(result).toBe(false);
    });
  });

  // ---------------------------------------------------------------------------
  // Migration Markers
  // ---------------------------------------------------------------------------

  describe("migration markers", () => {
    it("should return false for non-existent marker", async () => {
      const exists = await memory.hasMigrationMarker("nonexistent_key");
      expect(exists).toBe(false);
    });

    it("should set and detect marker", async () => {
      await memory.setMigrationMarker("test_marker_v1");
      const exists = await memory.hasMigrationMarker("test_marker_v1");
      expect(exists).toBe(true);
    });

    it("should be idempotent (setting same marker twice)", async () => {
      await memory.setMigrationMarker("idempotent_key", { attempt: 1 });
      await memory.setMigrationMarker("idempotent_key", { attempt: 2 });

      const exists = await memory.hasMigrationMarker("idempotent_key");
      expect(exists).toBe(true);
    });

    it("should store metadata with marker", async () => {
      const metadata = { migrated: 10, total: 15, skipped: 5 };
      await memory.setMigrationMarker("meta_key", metadata);

      const exists = await memory.hasMigrationMarker("meta_key");
      expect(exists).toBe(true);
    });

    it("should handle marker without metadata", async () => {
      await memory.setMigrationMarker("no_meta");
      const exists = await memory.hasMigrationMarker("no_meta");
      expect(exists).toBe(true);
    });

    it("should distinguish between different marker keys", async () => {
      await memory.setMigrationMarker("key_a");

      expect(await memory.hasMigrationMarker("key_a")).toBe(true);
      expect(await memory.hasMigrationMarker("key_b")).toBe(false);
    });
  });

  describe("HNSW recovery", () => {
    it("rebuilds persisted HNSW state from SQLite when reopened with a larger capacity", async () => {
      const reopenDir = mkdtempSync(join(tmpdir(), "agentdb-reopen-test-"));

      const initialMemory = new AgentDBMemory({
        dbPath: reopenDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 0,
          [MemoryTier.Ephemeral]: 0,
          [MemoryTier.Persistent]: 1,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
      });
      await initialMemory.initialize();
      await initialMemory.storeNote("Seed note", ["seed"]);
      await initialMemory.shutdown();

      const reopenedMemory = new AgentDBMemory({
        dbPath: reopenDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 10,
          [MemoryTier.Persistent]: 10,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
      });
      await reopenedMemory.initialize();

      try {
        await expect(reopenedMemory.storeNote("Follow-up note", ["follow-up"])).resolves.toBeDefined();

        const stats = reopenedMemory.getStats();
        expect(stats.totalEntries).toBe(2);
        expect(stats.hnswStats?.currentCount).toBe(2);
      } finally {
        await reopenedMemory.shutdown();
        rmSync(reopenDir, { recursive: true, force: true });
      }
    });
  });

  // ---------------------------------------------------------------------------
  // reEmbedHashEntries
  // ---------------------------------------------------------------------------

  describe("reEmbedHashEntries", () => {
    it("should skip when migration marker exists", async () => {
      // Pre-set the migration marker
      await memory.setMigrationMarker("re_embed_complete_v1");

      const result = await memory.reEmbedHashEntries();

      expect(result.migrated).toBe(0);
      expect(result.total).toBe(0);
      expect(result.skipped).toBe(0);
    });

    it("should return zeros when no embedding provider", async () => {
      // Default test config has no embeddingProvider
      // Store some entries so there's data to potentially migrate
      await memory.storeNote("Note to migrate", ["test"]);

      const result = await memory.reEmbedHashEntries();

      expect(result.migrated).toBe(0);
      expect(result.total).toBe(0);
      expect(result.skipped).toBe(0);
    });

    it("should set migration marker after completion", async () => {
      // Create memory with an embedding provider
      const memoryWithProvider = new AgentDBMemory({
        dbPath: mkdtempSync(join(tmpdir(), "agentdb-embed-test-")),
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 1000,
        embeddingProvider: async (_text: string) => {
          // Return an embedding with negative values (real embedding)
          return new Array(128).fill(0).map((_, i) => (i % 2 === 0 ? 0.1 : -0.1));
        },
      });
      await memoryWithProvider.initialize();

      try {
        await memoryWithProvider.reEmbedHashEntries();

        const markerExists = await memoryWithProvider.hasMigrationMarker("re_embed_complete_v1");
        expect(markerExists).toBe(true);
      } finally {
        const providerDir = (memoryWithProvider as any).config.dbPath;
        await memoryWithProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });

    it("should migrate hash-based entries when embedding provider is available", async () => {
      const providerDir = mkdtempSync(join(tmpdir(), "agentdb-migrate-test-"));
      let callCount = 0;

      // First create memory WITHOUT a provider to store hash-based entries
      const memoryNoProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
      });
      await memoryNoProvider.initialize();

      // Store entries that will get hash-based embeddings
      await memoryNoProvider.storeNote("First note about TypeScript", ["ts"]);
      await memoryNoProvider.storeNote("Second note about Python", ["py"]);
      await memoryNoProvider.shutdown();

      // Now reopen with a real embedding provider
      const memoryWithProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
        embeddingProvider: async (_text: string) => {
          callCount++;
          return new Array(128).fill(0).map((_, i) => (i % 2 === 0 ? 0.05 : -0.05));
        },
      });
      await memoryWithProvider.initialize();

      try {
        const result = await memoryWithProvider.reEmbedHashEntries();

        // Hash entries should have been detected and re-embedded
        expect(result.total).toBeGreaterThan(0);
        expect(result.migrated).toBeGreaterThan(0);
        expect(callCount).toBeGreaterThan(0);

        // Marker should be set
        const markerExists = await memoryWithProvider.hasMigrationMarker("re_embed_complete_v1");
        expect(markerExists).toBe(true);
      } finally {
        await memoryWithProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });

    it("should be idempotent (second call returns zeros)", async () => {
      const providerDir = mkdtempSync(join(tmpdir(), "agentdb-idem-test-"));
      const memoryWithProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
        embeddingProvider: async (_text: string) => {
          return new Array(128).fill(0).map((_, i) => (i % 2 === 0 ? 0.05 : -0.05));
        },
      });
      await memoryWithProvider.initialize();

      try {
        // First call performs migration
        await memoryWithProvider.reEmbedHashEntries();

        // Second call should be a no-op due to migration marker
        const result2 = await memoryWithProvider.reEmbedHashEntries();
        expect(result2.migrated).toBe(0);
        expect(result2.total).toBe(0);
        expect(result2.skipped).toBe(0);
      } finally {
        await memoryWithProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });

    it("should skip entries that already have real embeddings", async () => {
      const providerDir = mkdtempSync(join(tmpdir(), "agentdb-skip-test-"));
      let callCount = 0;

      // Create memory WITH provider from the start — entries get real embeddings
      const memoryWithProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
        embeddingProvider: async (_text: string) => {
          callCount++;
          return new Array(128).fill(0).map((_, i) => (i % 2 === 0 ? 0.05 : -0.05));
        },
      });
      await memoryWithProvider.initialize();

      try {
        // Store entries — these get real embeddings via the provider
        await memoryWithProvider.storeNote("Already real embedding", ["test"]);
        const callsAfterStore = callCount;

        const result = await memoryWithProvider.reEmbedHashEntries();

        // Entries with real embeddings should be skipped
        expect(result.skipped).toBeGreaterThanOrEqual(1);
        // No additional embedding calls should have been made for skipped entries
        expect(callCount).toBe(callsAfterStore);
      } finally {
        await memoryWithProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });

    it("should handle embedding provider failures gracefully", async () => {
      const providerDir = mkdtempSync(join(tmpdir(), "agentdb-fail-test-"));

      // Create without provider to get hash entries
      const memoryNoProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
      });
      await memoryNoProvider.initialize();
      await memoryNoProvider.storeNote("Entry that will fail re-embed", ["test"]);
      await memoryNoProvider.shutdown();

      // Reopen with a provider that always throws
      const memoryFailProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
        embeddingProvider: async () => {
          throw new Error("Provider unavailable");
        },
      });
      await memoryFailProvider.initialize();

      try {
        // Should not throw — failures are caught and skipped
        const result = await memoryFailProvider.reEmbedHashEntries();

        // Failed entries should be counted as skipped, not crash the migration
        expect(result.migrated).toBe(0);
        expect(result.skipped).toBeGreaterThan(0);
      } finally {
        await memoryFailProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });

    it("should not set the migration marker when SQLite persistence fails", async () => {
      const providerDir = mkdtempSync(join(tmpdir(), "agentdb-persist-fail-test-"));

      const memoryNoProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
      });
      await memoryNoProvider.initialize();
      await memoryNoProvider.storeNote("Entry that will fail to persist", ["test"]);
      await memoryNoProvider.shutdown();

      const memoryWithProvider = new AgentDBMemory({
        dbPath: providerDir,
        dimensions: 128,
        maxEntriesPerTier: {
          [MemoryTier.Working]: 10,
          [MemoryTier.Ephemeral]: 50,
          [MemoryTier.Persistent]: 100,
        },
        hnswParams: { efConstruction: 50, M: 8, efSearch: 32 },
        quantizationType: "none",
        cacheSize: 100,
        enableAutoTiering: true,
        ephemeralTtlMs: 60_000,
        embeddingProvider: async () =>
          new Array(128).fill(0).map((_, i) => (i % 2 === 0 ? 0.05 : -0.05)),
      });
      await memoryWithProvider.initialize();

      try {
        const sqliteDb = (memoryWithProvider as unknown as {
          sqliteDb: { transaction: (fn: () => void) => () => void };
        }).sqliteDb;
        sqliteDb.transaction = vi.fn(() => () => {
          throw new Error("disk full");
        });

        const result = await memoryWithProvider.reEmbedHashEntries();

        expect(result.migrated).toBe(0);
        expect(result.skipped).toBeGreaterThan(0);
        expect(await memoryWithProvider.hasMigrationMarker("re_embed_complete_v1")).toBe(false);
      } finally {
        await memoryWithProvider.shutdown();
        rmSync(providerDir, { recursive: true, force: true });
      }
    });
  });

  // ---------------------------------------------------------------------------
  // Security: secret sanitization on write paths
  // ---------------------------------------------------------------------------

  describe("secret sanitization (write paths)", () => {
    it("redacts OpenAI API keys embedded in note content before persisting", async () => {
      const leakedKey = "sk-proj-abc123DEF456ghi789JKL012mno345PQR678stu901VWX234";
      const content = `Here is my API key: ${leakedKey} — do not leak.`;

      const stored = await memory.storeNote(content, [], MemoryTier.Persistent);

      // Entry returned and roundtripped should have the key redacted.
      expect(stored.content).not.toContain(leakedKey);
      expect(stored.content).toContain("[REDACTED");

      const fetched = await memory.getById(stored.id);
      expect(fetched.kind).toBe("ok");
      if (fetched.kind === "ok" && fetched.value.kind === "some") {
        expect(fetched.value.value.content).not.toContain(leakedKey);
        expect(fetched.value.value.content).toContain("[REDACTED");
      }
    });

    it("redacts secrets in conversation user/assistant messages stored via storeConversation", async () => {
      const leakedKey = "sk-proj-abc123DEF456ghi789JKL012mno345PQR678stu901VWX234";
      const summary = `User leaked ${leakedKey} while asking a question`;

      const entry = await memory.storeConversation(
        "chat-sanitize-test" as unknown as import("../../types/index.js").ChatId,
        summary,
        [],
        MemoryTier.Working,
        {
          userMessage: `My key is ${leakedKey}`,
          assistantMessage: `I noticed the key ${leakedKey} — do not share it`,
        },
      );

      expect(entry.content).not.toContain(leakedKey);
      const meta = entry.metadata as Record<string, unknown>;
      if (typeof meta["userMessage"] === "string") {
        expect(meta["userMessage"]).not.toContain(leakedKey);
      }
      if (typeof meta["assistantMessage"] === "string") {
        expect(meta["assistantMessage"]).not.toContain(leakedKey);
      }
    });

    it("does not modify ID, tier, or other structural fields when sanitizing", async () => {
      const safeContent = "Just a safe note with no secrets.";
      const stored = await memory.storeNote(safeContent, ["tag1"], MemoryTier.Persistent);

      expect(stored.content).toBe(safeContent); // unchanged
      expect(stored.tier).toBe(MemoryTier.Persistent);
      expect(typeof stored.id).toBe("string");
      expect(stored.id.length).toBeGreaterThan(0);
    });

    it("sanitizes content exactly once (no double-redaction across memory + SQLite layers)", async () => {
      // Regression for review finding #1: before the fix, storeEntry sanitized
      // once in agentdb-memory.ts AND upsertEntryRow sanitized again in
      // agentdb-sqlite.ts — two passes over identical content. With the fix,
      // upsertEntryRow trusts the caller. We verify by spying on sanitizeSecrets
      // and asserting at most one call per string leaf of the stored content.
      const secretMod = await import("../../security/secret-sanitizer.js");
      const spy = vi.spyOn(secretMod, "sanitizeSecrets");
      try {
        const leaked = "sk-proj-doubleCheckABC123DEF456ghi789JKL012mno345PQR678stu";
        const content = `secret=${leaked}`;
        const stored = await memory.storeNote(content, [], MemoryTier.Persistent);

        // Content is redacted (sanitization happened at least once).
        expect(stored.content).not.toContain(leaked);
        expect(stored.content).toContain("[REDACTED");

        // Filter spy calls that received our exact input — the pre-fix code
        // path would have produced ≥2 such calls (one in storeEntry, one in
        // upsertEntryRow). The fixed code path must produce exactly 1 for the
        // content string itself. Metadata sanitization takes a different path
        // (sanitizeSecretsDeep walks an empty {} here, making no secret calls).
        const contentCalls = spy.mock.calls.filter(
          (args) => typeof args[0] === "string" && args[0].includes(leaked),
        );
        expect(contentCalls.length).toBeLessThanOrEqual(1);
      } finally {
        spy.mockRestore();
      }
    });
  });
});
