/**
 * Terminal Setup Wizard - Interactive readline-based first-time configuration.
 *
 * Provides a quick terminal alternative to the web-based SetupWizard.
 * Uses only Node.js built-ins (zero external dependencies).
 *
 * Security:
 * - Unity project paths must be absolute and inside the user's home directory.
 * - All .env values are sanitized against newline injection.
 */

import * as readline from "node:readline/promises";
import { stdin, stdout } from "node:process";
import * as os from "node:os";
import * as fs from "node:fs";
import * as path from "node:path";
import { spawn } from "node:child_process";

const MAX_RETRIES = 3;

export interface WizardAnswers {
  unityProjectPath: string;
  apiKey: string;
  provider: string;
  channel: string;
  language: string;
}

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

/**
 * Validate that a Unity project path is absolute, exists, is a directory,
 * and resides inside the user's home directory.
 */
export function validateUnityPath(inputPath: string): ValidationResult {
  if (!inputPath || inputPath.trim() === "") {
    return { valid: false, error: "Path cannot be empty." };
  }

  const trimmed = inputPath.trim();

  if (!path.isAbsolute(trimmed)) {
    return { valid: false, error: "Path must be absolute (e.g. /Users/you/MyGame)." };
  }

  let resolved: string;
  try {
    resolved = fs.realpathSync(trimmed);
  } catch {
    return { valid: false, error: `Path does not exist: ${trimmed}` };
  }

  const homedir = os.homedir();
  if (resolved !== homedir && !resolved.startsWith(homedir + "/")) {
    return { valid: false, error: `Path must be inside your home directory (${homedir}).` };
  }

  if (!fs.statSync(resolved).isDirectory()) {
    return { valid: false, error: "Path must be a directory." };
  }

  return { valid: true };
}

/**
 * Sanitise a value before embedding it in a .env file line.
 *
 * Strips carriage returns and newline characters to prevent injection
 * of extra lines into the .env file, then trims whitespace.
 */
export function sanitizeEnvValue(value: string): string {
  return String(value).replace(/[\r\n]/g, "").trim();
}

/**
 * Detect the AI provider from the API key prefix.
 *
 * - `sk-ant-` → Claude (Anthropic)
 * - `sk-proj-` → OpenAI (project-scoped)
 * - `AIza` → Gemini (Google)
 * - Fallback → Claude
 */
export function detectProvider(apiKey: string): string {
  if (apiKey.startsWith("sk-ant-")) return "claude";
  if (apiKey.startsWith("sk-proj-")) return "openai";
  if (apiKey.startsWith("AIza")) return "gemini";
  return "claude";
}

/**
 * Generate .env file content from wizard answers.
 */
export function generateEnvContent(answers: WizardAnswers): string {
  const lines: string[] = [
    "# Strada Brain Configuration",
    `# Generated by strada setup on ${new Date().toISOString()}`,
    "",
  ];

  lines.push(`UNITY_PROJECT_PATH=${sanitizeEnvValue(answers.unityProjectPath)}`);
  lines.push("");

  const provider = answers.provider;
  if (provider === "claude") {
    lines.push(`ANTHROPIC_API_KEY=${sanitizeEnvValue(answers.apiKey)}`);
    lines.push("PROVIDER_CHAIN=claude");
  } else if (provider === "openai") {
    lines.push(`OPENAI_API_KEY=${sanitizeEnvValue(answers.apiKey)}`);
    lines.push("PROVIDER_CHAIN=openai");
  } else if (provider === "gemini") {
    lines.push(`GEMINI_API_KEY=${sanitizeEnvValue(answers.apiKey)}`);
    lines.push("PROVIDER_CHAIN=gemini");
    lines.push("RAG_EMBEDDING_PROVIDER=gemini");
  }
  lines.push("");

  lines.push(`DEFAULT_CHANNEL=${sanitizeEnvValue(answers.channel)}`);
  lines.push(`LANGUAGE_PREFERENCE=${sanitizeEnvValue(answers.language)}`);
  lines.push("");

  lines.push("STREAMING_ENABLED=true");
  lines.push("REQUIRE_EDIT_CONFIRMATION=true");
  lines.push("DASHBOARD_ENABLED=true");
  lines.push("MULTI_AGENT_ENABLED=true");
  lines.push("LOG_LEVEL=info");
  lines.push("WEB_CHANNEL_PORT=3000");
  lines.push("DASHBOARD_PORT=3001");
  lines.push("");

  return lines.join("\n") + "\n";
}

/**
 * Ask a question with validation and retry logic.
 * Throws after MAX_RETRIES consecutive invalid answers.
 */
async function askWithRetry(
  rl: readline.Interface,
  question: string,
  validate: (input: string) => ValidationResult,
  retries = MAX_RETRIES,
): Promise<string> {
  for (let i = 0; i < retries; i++) {
    const answer = await rl.question(question);
    const result = validate(answer);
    if (result.valid) return answer.trim();
    console.error(`  \u2717 ${result.error}`);
    if (i < retries - 1) console.log("  Please try again.");
  }
  throw new Error("Maximum retries exceeded.");
}

/**
 * Attempt to open a URL in the user's default browser.
 * Fails silently if no browser can be launched.
 */
function openBrowser(url: string): void {
  const platform = process.platform;

  let proc;
  if (platform === "darwin") {
    proc = spawn("open", [url], { stdio: "ignore", detached: true });
  } else if (platform === "win32") {
    proc = spawn("cmd", ["/c", "start", url], { stdio: "ignore", detached: true });
  } else {
    proc = spawn("xdg-open", [url], { stdio: "ignore", detached: true });
  }

  proc.on("error", () => {
    console.log(`\n  Could not open browser automatically.`);
    console.log(`  Please open: ${url}\n`);
  });
  proc.unref();
}

/**
 * Run the interactive terminal setup wizard.
 *
 * Prompts the user for Unity project path, API key, channel, and language.
 * Writes a .env file with the collected configuration.
 * Alternatively, launches the web-based SetupWizard if the user prefers.
 */
export async function runTerminalWizard(): Promise<void> {
  const rl = readline.createInterface({ input: stdin, output: stdout });

  rl.on("close", () => {
    console.log("\n\nSetup cancelled.");
    process.exit(0);
  });

  try {
    console.log("\n\uD83E\uDD89 Strada Brain Setup");
    console.log("\u2501".repeat(30));
    console.log("");

    console.log("? Setup method:");
    console.log("  1) Terminal (quick setup)");
    console.log("  2) Web Browser (full setup)");
    const method = await rl.question("  Choose [1/2] (default: 1): ");

    if (method.trim() === "2") {
      rl.close();
      const port = process.env["SETUP_WIZARD_PORT"]
        ? parseInt(process.env["SETUP_WIZARD_PORT"], 10)
        : 3000;
      const { SetupWizard } = await import("./setup-wizard.js");
      const wizard = new SetupWizard({ port });
      const url = `http://localhost:${port}/setup`;
      console.log(`\n\uD83C\uDF10 Opening setup at ${url}...`);
      console.log(`   (Open this URL in your browser if it didn't open automatically)\n`);
      openBrowser(url);
      await wizard.start();
      return;
    }

    console.log("");

    const unityPath = await askWithRetry(
      rl,
      "? Unity project path: ",
      validateUnityPath,
    );

    const apiKey = await askWithRetry(
      rl,
      "? AI Provider API key (Claude/OpenAI/Gemini): ",
      (input) => {
        if (!input || input.trim().length < 8) {
          return { valid: false, error: "API key seems too short." };
        }
        return { valid: true };
      },
    );

    const provider = detectProvider(apiKey.trim());

    const channelAnswer = await rl.question("? Default channel (web): ");
    const channel = channelAnswer.trim() || "web";

    const langAnswer = await rl.question("? Language (en): ");
    const language = langAnswer.trim() || "en";

    const envPath = path.join(process.cwd(), ".env");
    if (fs.existsSync(envPath)) {
      const overwrite = await rl.question("\n\u26A0 .env already exists. Overwrite? [y/N]: ");
      if (overwrite.trim().toLowerCase() !== "y") {
        console.log("\nSetup cancelled. Existing .env preserved.");
        rl.close();
        return;
      }
    }

    const envContent = generateEnvContent({
      unityProjectPath: unityPath,
      apiKey: apiKey.trim(),
      provider,
      channel,
      language,
    });

    fs.writeFileSync(envPath, envContent, "utf-8");

    console.log(`\n\u2705 .env created! Run \`strada start\` to begin.\n`);
    rl.close();
  } catch (err) {
    rl.close();
    if ((err as Error).message === "Maximum retries exceeded.") {
      console.error("\nToo many invalid attempts. Please try again.");
      process.exit(1);
    }
    throw err;
  }
}
