/**
 * unity_prerender_frames — the prerendered-frames pipeline as a tool.
 *
 * The GDD's actual art spec ("plump, glossy 3D-feel ... with 2D-animation
 * snappiness") describes the casual-game industry standard: render a 3D
 * character once, ship glossy 2D frames. This tool runs the proven pipeline
 * against any prefab the agent points at: instantiate in a tuned 3-point-lit
 * scene, stylize for the game's look (chibi proportions + pastel toon-glossy
 * material + inverted-hull outline — measured on the boar cub: realistic
 * wild boar in, cartoon pig out), and capture N angles synchronously through
 * an offscreen RenderTexture (CaptureScreenshot never lands in batchmode).
 *
 * The editor script is written into the TARGET project for the run and
 * removed afterwards — the user's repo is not polluted.
 */

import { execFile } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, rmSync, readdirSync, statSync } from "node:fs";
import { join, basename } from "node:path";
import type { ITool, ToolContext, ToolExecutionResult } from "../tool.interface.js";
import { validatePath } from "../../../security/path-guard.js";
import { reuseOrMintGuid } from "./meta-file-utils.js";
import { spriteMeta } from "./sprite-generate.js";

const DEFAULT_CLI = process.env["STRADA_UNITY_CLI"] ?? "/Users/okan/.unity/bin/unity";

export interface PrerenderStyle {
  /** Pastel body color for the toon look (hex). */
  bodyColor?: string;
  /** Root squash for plumpness [x, y, z]. */
  plump?: [number, number, number];
  /** Head-bone scale multiplier. */
  headScale?: number;
  /** Outline width factor (0 disables the outline). */
  outlineWidth?: number;
}

function hexToRgb(hex: string | undefined, fallback: [number, number, number]): string {
  if (!hex) return `${fallback[0]}F, ${fallback[1]}F, ${fallback[2]}F`;
  const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex.trim());
  if (!m) return `${fallback[0]}F, ${fallback[1]}F, ${fallback[2]}F`;
  return `${(parseInt(m[1]!, 16) / 255).toFixed(3)}F, ${(parseInt(m[2]!, 16) / 255).toFixed(3)}F, ${(parseInt(m[3]!, 16) / 255).toFixed(3)}F`;
}

export function buildRenderScript(style: Required<PrerenderStyle>): string {
  const body = hexToRgb(undefined, [0.98, 0.62, 0.72]);
  const customBody = style.bodyColor !== undefined && style.bodyColor !== "" ? hexToRgb(style.bodyColor, [0.98, 0.62, 0.72]) : body;
  return `// Generated by unity_prerender_frames — one-shot render, deleted after the run.
using System;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class StradaPrerenderRun
{
    const float BodyR = 0f, BodyG = 0f, BodyB = 0f; // unused marker
    public static void Run()
    {
        var cmd = Environment.GetCommandLineArgs();
        string prefabPath = null, outDir = null;
        for (int i = 0; i < cmd.Length - 1; i++)
        {
            if (cmd[i] == "-prefab") prefabPath = cmd[i + 1];
            else if (cmd[i] == "-outDir") outDir = cmd[i + 1];
        }
        if (string.IsNullOrEmpty(prefabPath) || string.IsNullOrEmpty(outDir))
        {
            Debug.LogError("STRADA-RENDER-FAIL: missing -prefab/-outDir");
            EditorApplication.Exit(1);
            return;
        }
        Directory.CreateDirectory(outDir);

        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        var key = new GameObject("KeyLight").AddComponent<Light>();
        key.type = LightType.Directional; key.intensity = 0.7f; key.color = new Color(1f, 0.96f, 0.9f);
        key.transform.rotation = Quaternion.Euler(42f, -38f, 0f); key.shadows = LightShadows.Soft;
        var fill = new GameObject("FillLight").AddComponent<Light>();
        fill.type = LightType.Directional; fill.intensity = 0.3f; fill.color = new Color(0.82f, 0.88f, 1f);
        fill.transform.rotation = Quaternion.Euler(18f, 132f, 0f);
        var rim = new GameObject("RimLight").AddComponent<Light>();
        rim.type = LightType.Directional; rim.intensity = 0.35f; rim.color = new Color(1f, 0.85f, 0.95f);
        rim.transform.rotation = Quaternion.Euler(30f, 205f, 0f);
        RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Trilight;
        RenderSettings.ambientSkyColor = new Color(0.62f, 0.65f, 0.7f);
        RenderSettings.ambientEquatorColor = new Color(0.5f, 0.48f, 0.52f);
        RenderSettings.ambientGroundColor = new Color(0.3f, 0.28f, 0.32f);

        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
        if (prefab == null) { Debug.LogError("STRADA-RENDER-FAIL: prefab not found: " + prefabPath); EditorApplication.Exit(1); return; }
        var root = (GameObject)PrefabUtility.InstantiatePrefab(prefab, scene);
        root.transform.position = Vector3.zero;

        var ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
        ground.transform.position = new Vector3(0, -0.001f, 0);
        ground.transform.localScale = Vector3.one * 4f;
        ground.GetComponent<Renderer>().sharedMaterial = new Material(Shader.Find("Standard")) { color = new Color(0.9f, 0.9f, 0.93f) };

        StylizeForGame(root);

        var bounds = new Bounds(root.transform.position, Vector3.one);
        foreach (var r in root.GetComponentsInChildren<Renderer>()) bounds.Encapsulate(r.bounds);
        float radius = Mathf.Max(bounds.extents.magnitude, 0.35f);

        var camGo = new GameObject("RenderCam");
        var cam = camGo.AddComponent<Camera>();
        cam.fieldOfView = 30f; cam.nearClipPlane = 0.01f; cam.farClipPlane = 100f;
        cam.clearFlags = CameraClearFlags.SolidColor;
        cam.backgroundColor = new Color(0.93f, 0.94f, 0.97f);

        var rt = new RenderTexture(768, 768, 24, RenderTextureFormat.ARGB32);
        rt.antiAliasing = 4;
        cam.targetTexture = rt;
        var tex = new Texture2D(rt.width, rt.height, TextureFormat.RGBA32, false);

        var center = bounds.center;
        var angles = new[] { 0f, 45f, 90f, 135f, 180f, 270f };
        foreach (var deg in angles)
        {
            float rad = deg * Mathf.Deg2Rad;
            float dist = radius * 3.0f;
            camGo.transform.position = center + new Vector3(Mathf.Sin(rad) * dist, radius * 1.1f, Mathf.Cos(rad) * dist);
            camGo.transform.LookAt(center + Vector3.up * radius * 0.15f);
            cam.Render();
            RenderTexture.active = rt;
            tex.ReadPixels(new Rect(0, 0, rt.width, rt.height), 0, 0);
            tex.Apply();
            RenderTexture.active = null;
            File.WriteAllBytes(Path.Combine(outDir, $"frame_{deg:000}.png"), tex.EncodeToPNG());
        }
        cam.targetTexture = null;
        rt.Release();
        Debug.Log("STRADA-RENDER-OK: " + outDir);
        EditorApplication.Exit(0);
    }

    static void StylizeForGame(GameObject root)
    {
        root.transform.localScale = new Vector3(${style.plump[0].toFixed(2)}f, ${style.plump[1].toFixed(2)}f, ${style.plump[2].toFixed(2)}f);
        foreach (var t in root.GetComponentsInChildren<Transform>())
        {
            var n = t.name.ToLowerInvariant();
            if (n.Contains("head") && !n.Contains("headend"))
                t.localScale *= ${style.headScale.toFixed(2)}f;
        }

        const string shaderPath = "Assets/Editor/StradaOutline.shader";
        if (AssetDatabase.LoadAssetAtPath<Shader>(shaderPath) == null)
        {
            File.WriteAllText(shaderPath,
@"Shader ""Strada/Outline"" {
  Properties { _Color (""Color"", Color) = (0.12,0.08,0.1,1) _Width (""Width"", Float) = ${style.outlineWidth.toFixed(1)} }
  SubShader {
    Tags { ""Queue""=""Transparent"" }
    Pass {
      Cull Front
      CGPROGRAM
      #pragma vertex vert
      #pragma fragment frag
      float4 _Color; float _Width;
      struct appdata { float4 vertex : POSITION; float3 normal : NORMAL; };
      struct v2f { float4 pos : SV_POSITION; };
      v2f vert(appdata v) {
        v2f o;
        float3 n = normalize(v.normal) * (_Width * 0.012);
        o.pos = UnityObjectToClipPos(v.vertex.xyz + n);
        return o;
      }
      fixed4 frag(v2f i) : SV_Target { return _Color; }
      ENDCG
    }
  }
}");
            AssetDatabase.ImportAsset(shaderPath);
        }
        var outlineShader = AssetDatabase.LoadAssetAtPath<Shader>(shaderPath);

        var toon = new Material(Shader.Find("Standard"));
        toon.color = new Color(${customBody});
        toon.SetFloat("_Glossiness", 0.82f);
        toon.SetFloat("_Metallic", 0.0f);

        var darkGlossy = new Material(Shader.Find("Standard"));
        darkGlossy.color = new Color(0.1f, 0.08f, 0.1f);
        darkGlossy.SetFloat("_Glossiness", 0.9f);

        var outlineMat = new Material(outlineShader);
        foreach (var smr in root.GetComponentsInChildren<SkinnedMeshRenderer>())
        {
            bool isEye = smr.name.ToLowerInvariant().Contains("eye");
            smr.sharedMaterial = isEye ? darkGlossy : toon;
            if (${style.outlineWidth > 0 ? "true" : "false"})
            {
                var shell = new GameObject(smr.name + "_Outline");
                shell.transform.SetParent(smr.transform, false);
                var shellSmr = shell.AddComponent<SkinnedMeshRenderer>();
                shellSmr.bones = smr.bones;
                shellSmr.rootBone = smr.rootBone;
                shellSmr.sharedMesh = smr.sharedMesh;
                shellSmr.sharedMaterial = outlineMat;
                shellSmr.localBounds = smr.localBounds;
                shellSmr.updateWhenOffscreen = smr.updateWhenOffscreen;
            }
        }
    }
}
`;
}

export class PrerenderFramesTool implements ITool {
  readonly name = "unity_prerender_frames";
  readonly description =
    "Render glossy game-ready 2D frames of any prefab (the casual-game prerendered pipeline): " +
    "3-point-lit scene, game-style stylization (chibi proportions, pastel toon-glossy material, " +
    "inverted-hull outline), captured at 6 angles synchronously. Use after importing/sourcing a " +
    "rigged model (e.g. from unity_my_assets packages) — the realistic-to-cartoon transform is " +
    "built in. Writes frame_XXX.png under the output dir.";

  readonly inputSchema = {
    type: "object",
    properties: {
      prefab: { type: "string", description: "Project-relative prefab path, e.g. Assets/Realistic/.../Boar_cub_IP.prefab" },
      outDir: { type: "string", description: "Project-relative output dir under Assets/ (default: Assets/Art/Prerendered)" },
      bodyColor: { type: "string", description: "Toon body color #rrggbb (default pastel pink #f89eb8)" },
      outlineWidth: { type: "number", description: "Outline width factor (default 1.0; 0 disables)" },
      plumpness: { type: "number", description: "Body squash 0.5–1.5 (default 1.2 wide / 0.86 tall)" },
      headScale: { type: "number", description: "Head-bone scale multiplier (default 1.22)" },
    },
    required: ["prefab"],
  };

  async execute(input: Record<string, unknown>, context: ToolContext): Promise<ToolExecutionResult> {
    if (context.readOnly) {
      return { content: "Error: prerendering is disabled in read-only mode", isError: true };
    }

    const prefabRel = String(input["prefab"] ?? "").trim();
    if (!prefabRel.toLowerCase().endsWith(".prefab")) {
      return { content: "Error: prefab must be a .prefab path", isError: true };
    }
    const prefabCheck = await validatePath(context.projectPath, prefabRel);
    if (!prefabCheck.valid) return { content: `Error: ${prefabCheck.error ?? "prefab path invalid"}`, isError: true };
    if (!existsSync(prefabCheck.fullPath)) {
      return { content: `Error: prefab not found: ${prefabRel}`, isError: true };
    }

    // Per-prefab default: a shared constant dir + undiscriminated frame names
    // made a second prefab's run "succeed" instantly on the FIRST prefab's
    // stale frames.
    const prefabBase = basename(prefabRel).replace(/\.prefab$/i, "");
    const outRel = String(input["outDir"] ?? `Assets/Art/Prerendered/${prefabBase}`);
    if (!/^Assets([/\\]|$)/i.test(outRel.replace(/\\/g, "/")) && outRel !== "Assets") {
      return { content: "Error: outDir must be under Assets/", isError: true };
    }
    const outCheck = await validatePath(context.projectPath, outRel, { allowMissingParents: true });
    if (!outCheck.valid) return { content: `Error: ${outCheck.error ?? "outDir invalid"}`, isError: true };

    // Environment check AFTER input validation: bad inputs deserve their own
    // answer on every machine (the old order made validation untestable off
    // the dev box — the CLI-missing error answered first everywhere else).
    if (!existsSync(DEFAULT_CLI)) {
      return { content: `Error: Unity CLI not found at ${DEFAULT_CLI} — the Hub-launched editor is required for rendering.`, isError: true };
    }
    mkdirSync(outCheck.fullPath, { recursive: true });

    const outlineRaw = Number(input["outlineWidth"] ?? 1.0);
    const plumpRaw = Number(input["plumpness"] ?? 1.2);
    const headRaw = Number(input["headScale"] ?? 1.22);
    // The project's style.json (derived from ITS OWN GDD by style-analysis —
    // never a universal preset) supplies the defaults; explicit inputs win.
    let styleProfileDefaults: { bodyColor?: string; outlineWidth?: number; plump?: number; headScale?: number } = {};
    try {
      const { loadStyleProfile, familyDefaults } = await import("../../style/style-profile.js");
      const profile = loadStyleProfile(context.projectPath);
      if (profile) {
        const fam = familyDefaults(profile.family);
        styleProfileDefaults = {
          bodyColor: profile.palette[0],
          outlineWidth: profile.outline.width,
          plump: profile.proportions.plump,
          headScale: profile.proportions.headScale,
        };
        // Family defaults fill any profile gaps.
        if (styleProfileDefaults.outlineWidth === 0 && fam.outlineWidth !== 0 && profile.family !== "realistic") {
          styleProfileDefaults.outlineWidth = fam.outlineWidth;
        }
      }
    } catch {
      /* profile read is best-effort; explicit inputs and stock defaults still work */
    }
    const style: Required<PrerenderStyle> = {
      bodyColor: input["bodyColor"] !== undefined ? String(input["bodyColor"]) : (styleProfileDefaults.bodyColor ?? "#f89eb8"),
      outlineWidth: Number.isFinite(outlineRaw) ? Math.max(0, Math.min(3, outlineRaw)) : (styleProfileDefaults.outlineWidth ?? 1.0),
      plump: (() => {
        const p = Number.isFinite(plumpRaw) ? Math.min(1.5, Math.max(0.5, plumpRaw)) : (styleProfileDefaults.plump ?? 1.2);
        return [p, 0.86, p] as [number, number, number];
      })(),
      headScale: Number.isFinite(headRaw) ? Math.min(2, Math.max(0.5, headRaw)) : (styleProfileDefaults.headScale ?? 1.22),
    };

    const scriptRel = "Assets/Editor/StradaPrerenderRun.cs";
    const scriptCheck = await validatePath(context.projectPath, scriptRel, { allowMissingParents: true });
    if (!scriptCheck.valid) return { content: `Error: ${scriptCheck.error ?? "script path invalid"}`, isError: true };

    let succeeded = false;
    try {
      mkdirSync(join(context.projectPath, "Assets", "Editor"), { recursive: true });
      writeFileSync(scriptCheck.fullPath, buildRenderScript(style), "utf8");

      const unityArgs = `-batchmode -executeMethod StradaPrerenderRun.Run -prefab "${prefabRel}" -outDir "${outCheck.fullPath}" -logFile "${join(context.projectPath, "prerender.log")}"`;
      const logPath = join(context.projectPath, "prerender.log");
      if (existsSync(logPath)) rmSync(logPath, { force: true });
      execFile(DEFAULT_CLI, ["open", context.projectPath, "--args", unityArgs], { timeout: 60_000 }, () => undefined).unref?.();

      // `unity open` is fire-and-forget: the CLI returns while the editor is
      // still booting (and deleting the script here once cost a whole run).
      // The artifact is the signal, not the process — but only a FRESH
      // artifact: pre-existing frames from an earlier run must not read as
      // this run's success.
      const launchedAt = Date.now();
      const listFreshFrames = (): string[] =>
        existsSync(outCheck.fullPath)
          ? readdirSync(outCheck.fullPath).filter((f) => {
              if (!/^frame_\d+\.png$/.test(f)) return false;
              try {
                return statSync(join(outCheck.fullPath, f)).mtimeMs >= launchedAt - 2_000;
              } catch {
                return false;
              }
            })
          : [];
      const deadline = Date.now() + 30 * 60_000;
      let frames: string[] = [];
      let failDetail = "";
      while (Date.now() < deadline) {
        frames = listFreshFrames();
        if (frames.length > 0) break;
        if (existsSync(logPath)) {
          const log = (await import("node:fs")).readFileSync(logPath, "utf8");
          if (log.includes("STRADA-RENDER-FAIL")) {
            const m = /STRADA-RENDER-FAIL: ([^\n]+)/.exec(log);
            failDetail = m?.[1] ?? "render script failed";
            break;
          }
          if (log.includes("STRADA-RENDER-OK")) break;
          if (/error CS\d+/.test(log)) {
            const m = /(error CS\d+[^\n]*)/.exec(log);
            failDetail = `script compile error: ${m?.[1] ?? "unknown"}`;
            break;
          }
        }
        await new Promise((r) => setTimeout(r, 2000));
      }
      if (frames.length === 0 && failDetail === "") {
        // STRADA-RENDER-OK can land in the log a beat before the directory
        // listing catches up — one final look before declaring failure.
        frames = listFreshFrames();
      }
      if (frames.length === 0) {
        return {
          content: `Error: render produced no frames${failDetail ? `: ${failDetail}` : " (timed out waiting — see prerender.log)"}`,
          isError: true,
        };
      }
      // Sprite .meta per frame: with no editor importing inside a lease, a
      // meta-less PNG lands as a default Texture instead of a Sprite. Guids
      // are reused across regenerations so bindings never churn.
      for (const frame of frames) {
        const framePath = join(outCheck.fullPath, frame);
        try {
          writeFileSync(`${framePath}.meta`, spriteMeta(reuseOrMintGuid(`${framePath}.meta`)), "utf8");
        } catch {
          // Meta emission is best-effort per frame.
        }
      }
      succeeded = true;
      return {
        content:
          `${frames.length} frames rendered to ${outRel} (+ sprite .meta each): ${frames.join(", ")}. ` +
          "These are the glossy game-ready angles — use them as the element's view sprites, and animate " +
          "between them for the '2D-animation snappiness' the GDD asks for.",
      };
    } catch (err) {
      return { content: `Error: prerender failed: ${err instanceof Error ? err.message : String(err)}`, isError: true };
    } finally {
      // NOTHING from the one-shot run lingers in the user's repo: the script,
      // the outline shader it writes, and — on success — the root-level log.
      // On failure the log STAYS: the error message points the agent at it.
      try {
        rmSync(scriptCheck.fullPath, { force: true });
        rmSync(`${scriptCheck.fullPath}.meta`, { force: true });
        rmSync(join(context.projectPath, "Assets", "Editor", "StradaOutline.shader"), { force: true });
        rmSync(join(context.projectPath, "Assets", "Editor", "StradaOutline.shader.meta"), { force: true });
        if (succeeded) {
          rmSync(join(context.projectPath, "prerender.log"), { force: true });
        }
      } catch {
        /* cleanup best-effort */
      }
    }
  }
}
