/**
 * Unity Link — the ONE interactive step of the asset-store story.
 *
 * The headless my-assets-cloud flow needs a packman refresh token. Getting the
 * first one requires the user's interactive Unity sign-in consent — which only
 * the Editor can show properly. This runner generates a self-contained C#
 * consent script into a minimal scratch project and launches the editor
 * (batch mode, NOT -nographics so the sign-in dialog can appear). The script:
 *
 *   1. Reads UnityConnect's configuration (identity host, packages host,
 *      packman client key) via reflection — the same internal call the
 *      Enhanced Package Manager proved out.
 *   2. Calls UnityOAuth.GetAuthorizationCodeAsync("packman", cb) → the user's
 *      standard Unity sign-in dialog appears once.
 *   3. Exchanges the code at POST {identity}/v1/oauth2/token.
 *   4. Writes {refreshToken, identityHost, packagesHost, clientSecret, linkedAt}
 *      to a JSON file this runner then moves to ~/.strada/unity-asset-store.json
 *      (chmod 600) — after that, everything is headless refresh.
 */

import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, chmodSync, readdirSync } from "node:fs";
import { execFile } from "node:child_process";
import { join } from "node:path";
import { tmpdir, homedir } from "node:os";
import { z } from "zod";
import { getLoggerSafe } from "../../../utils/logger.js";

// =============================================================================
// CONSENT SCRIPT (self-contained C#, mirrors the proven reflection recipe)
// =============================================================================

export const CONSENT_SCRIPT = `// Generated by Strada.Brain Unity Link — one-time packman OAuth consent.
using System;
using System.IO;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;
using UnityEngine.Networking;

public static class StradaLinkConsent
{
    const string ClientId = "packman";
    const int CloudIdentityValue = 6;
    const int CloudPackagesApiValue = 11;
    const int CloudPackagesKeyValue = 12;

    static bool _done;
    static int _exitCode = 1;
    static string _outPath;

    [Serializable]
    class TokenResponse { public string access_token; public string refresh_token; public int expires_in; }

    public static void Run()
    {
        var args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == "-linkOutput") _outPath = args[i + 1];
        if (string.IsNullOrEmpty(_outPath))
        {
            Debug.LogError("UNITY-LINK-FAIL: no -linkOutput path");
            EditorApplication.Exit(1);
            return;
        }
        EditorApplication.update += Pump;
        Flow();
    }

    static void Pump()
    {
        if (!_done) return;
        EditorApplication.update -= Pump;
        EditorApplication.Exit(_exitCode);
    }

    static async void Flow()
    {
        try
        {
            var identityHost = GetConfigUrl(CloudIdentityValue) ?? "https://api.unity.com";
            var packagesHost = GetConfigUrl(CloudPackagesApiValue) ?? "https://packages-v2.unity.com";
            var clientSecret = GetConfigUrl(CloudPackagesKeyValue);
            if (string.IsNullOrEmpty(clientSecret))
                throw new Exception("UnityConnect CloudPackagesKey unavailable on this editor");

            var code = await GetAuthorizationCode();
            var tokens = await ExchangeCode(identityHost.TrimEnd('/'), code, clientSecret);
            var json = "{"
                + "\\"refreshToken\\":\\"" + tokens.refresh_token + "\\","
                + "\\"identityHost\\":\\"" + identityHost.TrimEnd('/') + "\\","
                + "\\"packagesHost\\":\\"" + packagesHost.TrimEnd('/') + "\\","
                + "\\"clientSecret\\":\\"" + clientSecret + "\\","
                + "\\"linkedAt\\":" + DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()
                + "}";
            File.WriteAllText(_outPath, json);
            Debug.Log("UNITY-LINK-OK");
            _exitCode = 0;
        }
        catch (Exception e)
        {
            Debug.LogError("UNITY-LINK-FAIL: " + e.Message);
            _exitCode = 1;
        }
        finally
        {
            _done = true;
        }
    }

    static string GetConfigUrl(int value)
    {
        try
        {
            var editorAssembly = typeof(UnityEditor.Editor).Assembly;
            var connectType = editorAssembly.GetType("UnityEditor.Connect.UnityConnect");
            var enumType = editorAssembly.GetType("UnityEditor.Connect.CloudConfigUrl");
            if (connectType == null || enumType == null) return null;
            var instanceProp = connectType.GetProperty("instance",
                BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
            var instance = instanceProp?.GetValue(null, null);
            if (instance == null) return null;
            foreach (var m in connectType.GetMethods(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            {
                if (m.Name != "GetConfigurationURL") continue;
                var ps = m.GetParameters();
                if (ps.Length == 1 && ps[0].ParameterType == enumType)
                    return m.Invoke(instance, new object[] { Enum.ToObject(enumType, value) }) as string;
            }
        }
        catch { }
        return null;
    }

    static Task<string> GetAuthorizationCode()
    {
        var tcs = new TaskCompletionSource<string>();
        try
        {
            var editorAssembly = typeof(UnityEditor.Editor).Assembly;
            var oauthType = editorAssembly.GetType("UnityEditor.Connect.UnityOAuth");
            if (oauthType == null)
                foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                {
                    if (asm.IsDynamic) continue;
                    oauthType = asm.GetType("UnityEditor.Connect.UnityOAuth");
                    if (oauthType != null) break;
                }
            if (oauthType == null) throw new Exception("UnityOAuth type not found");

            MethodInfo target = null;
            foreach (var m in oauthType.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
            {
                if (m.Name != "GetAuthorizationCodeAsync") continue;
                var ps = m.GetParameters();
                if (ps.Length == 2 && ps[0].ParameterType == typeof(string)) { target = m; break; }
            }
            if (target == null) throw new Exception("GetAuthorizationCodeAsync(string, Action<>) not found");

            var responseType = target.GetParameters()[1].ParameterType.GetGenericArguments()[0];
            Action<object> handler = (resp) =>
            {
                var prop = responseType.GetProperty("code", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                        ?? responseType.GetProperty("Code", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                var field = responseType.GetField("code", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                        ?? responseType.GetField("Code", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                var code = prop != null ? prop.GetValue(resp, null) as string
                         : field != null ? field.GetValue(resp) as string : null;
                if (string.IsNullOrEmpty(code)) tcs.TrySetException(new Exception("empty authorization code"));
                else tcs.TrySetResult(code);
            };
            var del = Delegate.CreateDelegate(target.GetParameters()[1].ParameterType, handler.Target, handler.Method);
            target.Invoke(null, new object[] { ClientId, del });
        }
        catch (Exception e)
        {
            tcs.TrySetException(e);
        }
        return tcs.Task;
    }

    static async Task<TokenResponse> ExchangeCode(string tokenUrl, string code, string clientSecret)
    {
        var form = new WWWForm();
        form.AddField("grant_type", "authorization_code");
        form.AddField("code", code);
        form.AddField("client_id", ClientId);
        form.AddField("client_secret", clientSecret);
        using (var req = UnityWebRequest.Post(tokenUrl + "/v1/oauth2/token", form))
        {
            var op = req.SendWebRequest();
            while (!op.isDone) await Task.Yield();
            if (req.result != UnityWebRequest.Result.Success)
                throw new Exception("token exchange failed: " + req.error + " " + req.downloadHandler.text);
            return JsonUtility.FromJson<TokenResponse>(req.downloadHandler.text);
        }
    }
}
`;

// =============================================================================
// RUNNER
// =============================================================================

const linkSchema = z.object({
  refreshToken: z.string().min(10),
  identityHost: z.string().url().startsWith("https://"),
  packagesHost: z.string().url().startsWith("https://"),
  clientSecret: z.string().min(1),
  linkedAt: z.number(),
});

export interface UnityLinkResult {
  ok: boolean;
  detail: string;
  linkFile?: string;
}

export interface UnityLinkRunnerOptions {
  unityBin?: string;
  timeoutMs?: number;
  /** Test seam: replace the Unity process spawn. */
  spawnImpl?: typeof execFile;
}

const DEFAULT_UNITY_BIN = "/Applications/Unity/Hub/Editor/6000.3.22f1/Unity.app/Contents/MacOS/Unity";
const LINK_STORE = join(homedir(), ".strada", "unity-asset-store.json");

/** Read ProjectVersion from a real project if present, else the default. */
function editorVersion(): string {
  try {
    const v = readFileSync(
      "/Users/okan/Documents/MaxedOutEntertainment/PixelFlow-Clean/ProjectSettings/ProjectVersion.txt",
      "utf8",
    );
    const m = /m_EditorVersion:\s*(\S+)/.exec(v);
    if (m) return m[1]!;
  } catch {
    /* fall through */
  }
  return "6000.3.22f1";
}

export async function runUnityLink(options: UnityLinkRunnerOptions = {}): Promise<UnityLinkResult> {
  const unityBin = options.unityBin ?? resolveUnityBin();
  if (!existsSync(unityBin)) {
    return { ok: false, detail: `Unity editor not found at ${unityBin}` };
  }

  const scratch = mkdtempSync(join(tmpdir(), "strada-unity-link-"));
  const outputPath = join(scratch, "link-result.json");
  const logPath = join(scratch, "editor.log");
  const timeoutMs = options.timeoutMs ?? 5 * 60_000;

  try {
    mkdirSync(join(scratch, "Assets", "Editor"), { recursive: true });
    mkdirSync(join(scratch, "ProjectSettings"), { recursive: true });
    writeFileSync(join(scratch, "Assets", "Editor", "StradaLinkConsent.cs"), CONSENT_SCRIPT, "utf8");
    writeFileSync(
      join(scratch, "ProjectSettings", "ProjectVersion.txt"),
      `m_EditorVersion: ${editorVersion()}\n`,
      "utf8",
    );

    const spawn = options.spawnImpl ?? execFile;
    const exitCode = await new Promise<number>((resolvePromise) => {
      const child = spawn(
        unityBin,
        [
          "-batchmode",
          "-projectPath", scratch,
          "-executeMethod", "StradaLinkConsent.Run",
          "-logFile", logPath,
          "-linkOutput", outputPath,
        ],
        { timeout: timeoutMs },
        (error) => {
          if (error) {
            resolvePromise(typeof error.code === "number" ? error.code : 1);
          } else {
            resolvePromise(0);
          }
        },
      );
      child.unref?.();
    });

    if (exitCode !== 0 || !existsSync(outputPath)) {
      const logTail = existsSync(logPath)
        ? readFileSync(logPath, "utf8").split("\n").filter((l) => l.includes("UNITY-LINK")).slice(-3).join(" | ")
        : "no editor log";
      return { ok: false, detail: `Unity link failed (exit ${exitCode}): ${logTail}` };
    }

    const parsed = linkSchema.safeParse(JSON.parse(readFileSync(outputPath, "utf8")));
    if (!parsed.success) {
      return { ok: false, detail: `Unity link wrote an invalid token file: ${z.prettifyError(parsed.error).slice(0, 200)}` };
    }

    mkdirSync(join(homedir(), ".strada"), { recursive: true });
    writeFileSync(LINK_STORE, JSON.stringify(parsed.data, null, 2), { mode: 0o600 });
    chmodSync(LINK_STORE, 0o600);
    getLoggerSafe().info("Unity account linked for Asset Store access", { linkFile: LINK_STORE });
    return { ok: true, detail: `Unity account linked. Token store: ${LINK_STORE}`, linkFile: LINK_STORE };
  } catch (err) {
    return { ok: false, detail: `Unity link failed: ${err instanceof Error ? err.message : String(err)}` };
  } finally {
    try {
      rmSync(scratch, { recursive: true, force: true });
    } catch {
      /* scratch cleanup is best-effort */
    }
  }
}

function resolveUnityBin(): string {
  const editorsDir = "/Applications/Unity/Hub/Editor";
  try {
    const versions = readdirSync(editorsDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort()
      .reverse();
    if (versions.length > 0) {
      return join(editorsDir, versions[0]!, "Unity.app", "Contents", "MacOS", "Unity");
    }
  } catch {
    /* fall back to the default path */
  }
  return DEFAULT_UNITY_BIN;
}
