/**
 * Unity Link — the ONE interactive step of the asset-store story.
 *
 * The headless my-assets-cloud flow needs a packman refresh token. Getting the
 * first one requires the user's interactive Unity sign-in consent — which only
 * the Editor can show properly. This runner generates a self-contained C#
 * consent script into a minimal scratch project and launches the editor
 * (batch mode, NOT -nographics so the sign-in dialog can appear). The script:
 *
 *   1. Reads UnityConnect's configuration (identity host, packages host,
 *      packman client key) via reflection — the same internal call the
 *      Enhanced Package Manager proved out.
 *   2. Calls UnityOAuth.GetAuthorizationCodeAsync("packman", cb) → the user's
 *      standard Unity sign-in dialog appears once.
 *   3. Exchanges the code at POST {identity}/v1/oauth2/token.
 *   4. Writes {refreshToken, identityHost, packagesHost, clientSecret, linkedAt}
 *      to a JSON file this runner then moves to ~/.strada/unity-asset-store.json
 *      (chmod 600) — after that, everything is headless refresh.
 */

import { mkdirSync, writeFileSync, readFileSync, existsSync, rmSync, chmodSync, readdirSync } from "node:fs";
import { execFile } from "node:child_process";
import { join, dirname } from "node:path";
import { homedir } from "node:os";
import { z } from "zod";
import { getLoggerSafe } from "../../../utils/logger.js";

// =============================================================================
// CONSENT SCRIPT (self-contained C#, mirrors the proven reflection recipe)
// =============================================================================

export const CONSENT_SCRIPT = `// Generated by Strada.Brain Unity Link — one-time packman OAuth consent (code step only).
// The code EXCHANGE is done outside the editor: the editor's UnityConnect config
// (CloudPackagesApi/CloudPackagesKey) is only populated for Hub-launched editors
// (measured 2026-08-27 on 6000.3.22f1), so the runner reads the same values from
// the Hub's own cloudConfig.json and does the HTTPS exchange itself.
using System;
using System.IO;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using UnityEditor;
using UnityEngine;

public static class StradaLinkConsent
{
    const string ClientId = "packman";

    static bool _done;
    static int _exitCode = 1;
    static string _outPath;

    public static void Run()
    {
        Debug.Log("UNITY-LINK-START");
        var args = Environment.GetCommandLineArgs();
        for (int i = 0; i < args.Length - 1; i++)
            if (args[i] == "-linkOutput") _outPath = args[i + 1];
        if (string.IsNullOrEmpty(_outPath))
        {
            Debug.LogError("UNITY-LINK-FAIL: no -linkOutput path");
            EditorApplication.Exit(1);
            return;
        }
        EditorApplication.update += Pump;
        Flow();
    }

    static void Pump()
    {
        if (!_done) return;
        EditorApplication.update -= Pump;
        EditorApplication.Exit(_exitCode);
    }

    static async void Flow()
    {
        try
        {
            var code = await GetAuthorizationCode();
            File.WriteAllText(_outPath, "{\\"code\\":\\"" + code + "\\"}");
            Debug.Log("UNITY-LINK-OK");
            _exitCode = 0;
        }
        catch (Exception e)
        {
            Debug.LogError("UNITY-LINK-FAIL: " + e.Message);
            _exitCode = 1;
        }
        finally
        {
            _done = true;
        }
    }

    static Task<string> GetAuthorizationCode()
    {
        var tcs = new TaskCompletionSource<string>();
        try
        {
            var editorAssembly = typeof(UnityEditor.Editor).Assembly;
            var oauthType = editorAssembly.GetType("UnityEditor.Connect.UnityOAuth");
            if (oauthType == null)
                foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
                {
                    if (asm.IsDynamic) continue;
                    oauthType = asm.GetType("UnityEditor.Connect.UnityOAuth");
                    if (oauthType != null) break;
                }
            if (oauthType == null) throw new Exception("UnityOAuth type not found");

            MethodInfo target = null;
            foreach (var m in oauthType.GetMethods(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
            {
                if (m.Name != "GetAuthorizationCodeAsync") continue;
                var ps = m.GetParameters();
                if (ps.Length == 2 && ps[0].ParameterType == typeof(string)) { target = m; break; }
            }
            if (target == null) throw new Exception("GetAuthorizationCodeAsync(string, Action<>) not found");

            var responseType = target.GetParameters()[1].ParameterType.GetGenericArguments()[0];
            Action<object> handler = (resp) =>
            {
                // The callback delivers the code AS A STRING (measured live:
                // resp was System.String, 26 chars — not an object with a
                // .code property). Check that first; object shapes fall back
                // to property reading below.
                if (resp is string codeString && !string.IsNullOrEmpty(codeString))
                {
                    tcs.TrySetResult(codeString);
                    return;
                }
                // Read against the RUNTIME type: the declared Action<T> generic
                // arg and the delivered object can differ (TargetException,
                // measured 2026-08-27), and reading properties of the declared
                // type against the runtime object is what blew up the first pass.
                var actualType = resp.GetType();
                string code = null;
                foreach (var name in new[] { "code", "Code", "authCode", "AuthCode", "authorizationCode", "AuthorizationCode" })
                {
                    try
                    {
                        var prop = actualType.GetProperty(name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                        if (prop != null) { code = prop.GetValue(resp, null) as string; if (!string.IsNullOrEmpty(code)) break; }
                        var field = actualType.GetField(name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                        if (field != null) { code = field.GetValue(resp) as string; if (!string.IsNullOrEmpty(code)) break; }
                    }
                    catch { /* try the next name */ }
                }
                if (!string.IsNullOrEmpty(code))
                {
                    tcs.TrySetResult(code);
                    return;
                }
                // Diagnostic: the actual shape of the response, so a failure
                // names the real property instead of "empty".
                var sb = new StringBuilder();
                sb.Append("type=").Append(actualType.FullName).Append("; ");
                foreach (var p in actualType.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    object v = null;
                    try { v = p.GetValue(resp, null); } catch { }
                    sb.Append(p.Name).Append("=").Append(v == null ? "null" : (v is string s && s.Length > 40 ? s.Substring(0, 40) + "…" : v.ToString())).Append("; ");
                }
                foreach (var f in actualType.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
                {
                    object v = null;
                    try { v = f.GetValue(resp); } catch { }
                    sb.Append(f.Name).Append("=").Append(v == null ? "null" : (v is string s2 && s2.Length > 40 ? s2.Substring(0, 40) + "…" : v.ToString())).Append("; ");
                }
                tcs.TrySetException(new Exception("empty authorization code. Response shape: " + sb));
            };
            var del = Delegate.CreateDelegate(target.GetParameters()[1].ParameterType, handler.Target, handler.Method);
            try
            {
                target.Invoke(null, new object[] { ClientId, del });
            }
            catch (Exception invokeError)
            {
                // MethodInfo.Invoke wraps the real error — surface the inner one.
                var inner = invokeError.InnerException != null ? invokeError.InnerException : invokeError;
                throw new Exception("GetAuthorizationCodeAsync failed: " + inner.GetType().Name + ": " + inner.Message);
            }
        }
        catch (Exception e)
        {
            tcs.TrySetException(e);
        }
        return tcs.Task;
    }
}
`;

// =============================================================================
// RUNNER
// =============================================================================

const linkSchema = z.object({
  refreshToken: z.string().min(10),
  identityHost: z.string().url().startsWith("https://"),
  packagesHost: z.string().url().startsWith("https://"),
  clientSecret: z.string().min(1),
  linkedAt: z.number(),
});

const codeSchema = z.object({ code: z.string().min(10) });

/**
 * The Hub's own services configuration — the same source a Hub-launched
 * editor's UnityConnect config is fed from (measured 2026-08-27: a bare
 * batchmode editor has CloudPackagesApi/CloudPackagesKey EMPTY, this file
 * has them). Read locally, used for the user's own account, never leaves
 * the machine.
 */
function readHubCloudConfig(): { identityHost: string; packagesHost: string; clientSecret: string } | undefined {
  try {
    const path = join(homedir(), "Library", "Application Support", "UnityHub", "cloudConfig.json");
    const raw = JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>;
    const identity = raw["identity"] ?? raw["genesis_api_url"];
    const packages = raw["asset_store_api"];
    const key = raw["packman_key"];
    if (
      typeof identity !== "string" || !identity.startsWith("https://") ||
      typeof packages !== "string" || !packages.startsWith("https://") ||
      typeof key !== "string" || key.length === 0
    ) {
      return undefined;
    }
    return { identityHost: identity, packagesHost: packages, clientSecret: key };
  } catch {
    return undefined;
  }
}

/** Exchange the authorization code for packman tokens (plain HTTPS, no editor). */
async function exchangeCode(
  code: string,
  config: { identityHost: string; packagesHost: string; clientSecret: string },
): Promise<z.infer<typeof linkSchema>> {
  const body =
    "grant_type=authorization_code" +
    `&code=${encodeURIComponent(code)}` +
    "&client_id=packman" +
    `&client_secret=${encodeURIComponent(config.clientSecret)}`;
  const resp = await fetch(`${config.identityHost}/v1/oauth2/token`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!resp.ok) {
    throw new Error(`token exchange failed (HTTP ${resp.status}): ${(await resp.text()).slice(0, 200)}`);
  }
  const data = (await resp.json()) as Record<string, unknown>;
  const refreshToken = data["refresh_token"];
  if (typeof refreshToken !== "string" || refreshToken.length < 10) {
    throw new Error("token exchange returned no refresh_token");
  }
  return {
    refreshToken,
    identityHost: config.identityHost,
    packagesHost: config.packagesHost,
    clientSecret: config.clientSecret,
    linkedAt: Date.now(),
  };
}

export interface UnityLinkResult {
  ok: boolean;
  detail: string;
  linkFile?: string;
}

export interface UnityLinkRunnerOptions {
  unityBin?: string;
  unityCli?: string;
  timeoutMs?: number;
  /** Test seam: replace the Unity process spawn. */
  spawnImpl?: typeof execFile;
  /** Test seam: replace the wait-for-output polling. */
  waitForOutputImpl?: (path: string, timeoutMs: number) => Promise<boolean>;
  /** Test seam: where to write the resulting link. Tests MUST set this —
   *  writing the real ~/.strada store from a test overwrites the user's live
   *  refresh token with fixture data and destroys the account link. */
  linkStorePath?: string;
}

const DEFAULT_UNITY_BIN =
  process.env["STRADA_UNITY_BIN"] ?? "/Applications/Unity/Hub/Editor/6000.3.22f1/Unity.app/Contents/MacOS/Unity";
const DEFAULT_UNITY_CLI = process.env["STRADA_UNITY_CLI"] ?? "/Users/okan/.unity/bin/unity";
const LINK_STORE = join(homedir(), ".strada", "unity-asset-store.json");

/**
 * Wait for the consent output file. `unity open` is fire-and-forget (the Hub
 * launches the editor detached), so the editor's own exit is not observable —
 * the artifact it writes is the signal. Fail-fast on the FAIL log marker.
 */
async function defaultWaitForOutput(outputPath: string, logPath: string, timeoutMs: number): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (existsSync(outputPath)) return true;
    if (existsSync(logPath)) {
      const log = readFileSync(logPath, "utf8");
      if (log.includes("UNITY-LINK-FAIL")) return false;
      if (log.includes("User is not logged in")) return false;
    }
    await new Promise((r) => setTimeout(r, 2000));
  }
  return false;
}

/** Read ProjectVersion from the configured project if present, else the default. */
function editorVersion(): string {
  const projectRoot = process.env["UNITY_PROJECT_PATH"] ?? process.env["STRADA_UNITY_PROJECT"];
  if (projectRoot) {
    try {
      const v = readFileSync(join(projectRoot, "ProjectSettings", "ProjectVersion.txt"), "utf8");
      const m = /m_EditorVersion:\s*(\S+)/.exec(v);
      if (m) return m[1]!;
    } catch {
      /* fall through */
    }
  }
  return "6000.3.22f1";
}

export async function runUnityLink(options: UnityLinkRunnerOptions = {}): Promise<UnityLinkResult> {
  const unityCli = options.unityCli ?? (existsSync(DEFAULT_UNITY_CLI) ? DEFAULT_UNITY_CLI : undefined);
  const unityBin = options.unityBin ?? resolveUnityBin();
  if (unityCli !== undefined && !existsSync(unityCli)) {
    return { ok: false, detail: `Unity CLI not found at ${unityCli}` };
  }
  if (!unityCli && !existsSync(unityBin)) {
    return { ok: false, detail: `Unity editor not found at ${unityBin}` };
  }

  // PERSISTENT scratch (not tmp): the first editor import of the built-in
  // packages takes 3-4 minutes and repeatedly timed out the run when the
  // scratch was deleted every attempt (measured 2026-08-27). A stable path
  // pays that cost once; later runs boot in seconds.
  const scratch = join(homedir(), ".strada", "unity-link-project");
  const outputPath = join(scratch, "link-result.json");
  const logPath = join(scratch, "editor.log");
  const timeoutMs = options.timeoutMs ?? 10 * 60_000;

  try {
    mkdirSync(join(scratch, "Assets", "Editor"), { recursive: true });
    mkdirSync(join(scratch, "ProjectSettings"), { recursive: true });
    writeFileSync(join(scratch, "Assets", "Editor", "StradaLinkConsent.cs"), CONSENT_SCRIPT, "utf8");
    if (!existsSync(join(scratch, "ProjectSettings", "ProjectVersion.txt"))) {
      writeFileSync(
        join(scratch, "ProjectSettings", "ProjectVersion.txt"),
        `m_EditorVersion: ${editorVersion()}\n`,
        "utf8",
      );
    }
    // A previous attempt's result must not pass for a fresh one.
    if (existsSync(outputPath)) rmSync(outputPath, { force: true });

    // The editor needs the user's Hub session to run the OAuth dialog ("User
    // is not logged in" otherwise, measured 2026-08-27). The Hub passes that
    // session at LAUNCH — so the CLI's `open` path is mandatory, a bare
    // editor binary launch cannot work.
    const spawn = options.spawnImpl ?? execFile;
    if (unityCli) {
      const unityArgs = `-batchmode -executeMethod StradaLinkConsent.Run -logFile "${logPath}" -linkOutput "${outputPath}"`;
      const launchError = await new Promise<Error | null>((resolvePromise) => {
        try {
          spawn(unityCli, ["open", scratch, "--args", unityArgs], { timeout: 60_000 }, (err) => {
            resolvePromise(err);
          }).unref?.();
        } catch (err) {
          resolvePromise(err instanceof Error ? err : new Error(String(err)));
        }
      });
      // execFile reports a missing/unrunnable binary asynchronously; a clean
      // exit (even a nonzero one) just means the Hub took over — keep waiting.
      if (launchError && (launchError as NodeJS.ErrnoException).code === "ENOENT") {
        return { ok: false, detail: `Unity CLI could not be launched: ${launchError.message}` };
      }
    } else {
      return { ok: false, detail: "Unity CLI not found — the Hub session is required for the sign-in dialog." };
    }

    const gotOutput = options.waitForOutputImpl
      ? await options.waitForOutputImpl(outputPath, timeoutMs)
      : await defaultWaitForOutput(outputPath, logPath, timeoutMs);

    if (!gotOutput) {
      const logTail = existsSync(logPath)
        ? readFileSync(logPath, "utf8").split("\n").filter((l) => l.includes("UNITY-LINK") || l.includes("not logged in")).slice(-3).join(" | ")
        : "no editor log (sign-in may have been abandoned)";
      return { ok: false, detail: `Unity link did not complete: ${logTail}` };
    }

    // The editor only delivers the authorization CODE; the exchange happens
    // here with the Hub's own config (see readHubCloudConfig).
    const parsedCode = codeSchema.safeParse(JSON.parse(readFileSync(outputPath, "utf8")));
    if (!parsedCode.success) {
      return { ok: false, detail: "Unity link wrote no usable authorization code" };
    }
    const config = readHubCloudConfig();
    if (!config) {
      return { ok: false, detail: "Unity Hub cloud config not found (identity/asset_store_api/packman_key) — is the Hub installed and signed in?" };
    }

    let link: z.infer<typeof linkSchema>;
    try {
      link = await exchangeCode(parsedCode.data.code, config);
    } catch (err) {
      return { ok: false, detail: err instanceof Error ? err.message : String(err) };
    }
    const parsed = linkSchema.safeParse(link);
    if (!parsed.success) {
      return { ok: false, detail: `token exchange produced an invalid link: ${z.prettifyError(parsed.error).slice(0, 200)}` };
    }

    const linkStore = options.linkStorePath ?? LINK_STORE;
    if (
      linkStore === LINK_STORE &&
      (process.env["VITEST"] !== undefined || process.env["NODE_ENV"] === "test")
    ) {
      // Measured live 2026-08-28: the "stores the link" unit test overwrote
      // the user's REAL link store with fixture data and left it there —
      // silently killing the account link on every full-suite run.
      return { ok: false, detail: "refused under test: pass linkStorePath — writing the real ~/.strada store from a test destroys the user's Unity link" };
    }
    mkdirSync(dirname(linkStore), { recursive: true });
    writeFileSync(linkStore, JSON.stringify(parsed.data, null, 2), { mode: 0o600 });
    chmodSync(linkStore, 0o600);
    getLoggerSafe().info("Unity account linked for Asset Store access", { linkFile: linkStore });
    return { ok: true, detail: `Unity account linked. Token store: ${linkStore}`, linkFile: linkStore };
  } catch (err) {
    return { ok: false, detail: `Unity link failed: ${err instanceof Error ? err.message : String(err)}` };
  } finally {
    // The one-time authorization code must not linger on disk (it was left
    // world-readable until the NEXT run deleted it). The scratch project
    // itself stays — Library reuse, see above.
    try {
      rmSync(outputPath, { force: true });
    } catch {
      /* best-effort */
    }
  }
}

function resolveUnityBin(): string {
  const editorsDir = "/Applications/Unity/Hub/Editor";
  try {
    const versions = readdirSync(editorsDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort()
      .reverse();
    if (versions.length > 0) {
      return join(editorsDir, versions[0]!, "Unity.app", "Contents", "MacOS", "Unity");
    }
  } catch {
    /* fall back to the default path */
  }
  return DEFAULT_UNITY_BIN;
}
